Repository Tinkoff/kora, pull requests merged in 2023-08, with the labels that each got.

#231 Kotlin Retry Aspect simplified
  resilient/resilient-symbol-processor/src/main/kotlin/ru/tinkoff/kora/resilient/symbol/processor/aop/RetryableKoraAspect.kt
Labels: bug, lang: kotlin

#139 Declarative logging module
  annotation-processor-common/src/testFixtures/java/ru/tinkoff/kora/annotation/processor/common/AbstractAnnotationProcessorTest.java
  annotation-processors/build.gradle
  aop/aop-symbol-processor/src/main/kotlin/ru/tinkoff/kora/aop/symbol/processor/AopProcessor.kt
  aop/aop-symbol-processor/src/main/kotlin/ru/tinkoff/kora/aop/symbol/processor/AopSymbolProcessor.kt
  build.gradle
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/AbstractRepositoryTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/cassandra/AbstractCassandraRepositoryTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/cassandra/CassandraParametersTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/cassandra/CassandraResultsTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/AbstractJdbcRepositoryTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcParametersTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/jdbc/JdbcResultsTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/r2dbc/AbstractR2dbcRepositoryTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/r2dbc/R2dbcParametersTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/r2dbc/R2dbcResultsTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/vertx/AbstractVertxRepositoryTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/vertx/VertxParametersTest.java
  database/database-annotation-processor/src/test/java/ru/tinkoff/kora/database/common/annotation/processor/vertx/VertxResultsTest.java
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/AbstractRepositoryTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraParametersTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/cassandra/CassandraResultsTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcParametersTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/jdbc/JdbcResultsTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2dbcParametersTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/r2dbc/R2dbcResultsTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxParametersTest.kt
  database/database-symbol-processor/src/test/kotlin/ru/tinkoff/kora/database/symbol/processor/vertx/VertxResultsTest.kt
  logging/declarative-logging/declarative-logging-annotation-processor/build.gradle
  logging/declarative-logging/declarative-logging-annotation-processor/src/main/java/ru/tinkoff/kora/logging/aspect/LogAspect.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/main/java/ru/tinkoff/kora/logging/aspect/LogAspectClassNames.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/main/java/ru/tinkoff/kora/logging/aspect/LogAspectFactory.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/main/java/ru/tinkoff/kora/logging/aspect/LogAspectUtils.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/main/resources/META-INF/services/ru.tinkoff.kora.aop.annotation.processor.KoraAspectFactory
  logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/AbstractLogAspectTest.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/LogAspectReactiveTest.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/LogAspectTest.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/LogAspectTestOld.java
  logging/declarative-logging/declarative-logging-annotation-processor/src/test/java/ru/tinkoff/kora/logging/aspect/target/LogAspectTarget.java
  logging/declarative-logging/declarative-logging-symbol-processor/build.gradle
  logging/declarative-logging/declarative-logging-symbol-processor/src/main/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogKoraAspect.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/main/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogKoraAspectFactory.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/main/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/data/MethodData.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/main/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/data/MethodParameterData.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/main/resources/META-INF/services/ru.tinkoff.kora.aop.symbol.processor.KoraAspectFactory
  logging/declarative-logging/declarative-logging-symbol-processor/src/test/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/AbstractLogAspectTest.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/test/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogAspectSuspendTest.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/test/kotlin/ru/tinkoff/kora/logging/symbol/processor/aop/LogAspectTest.kt
  logging/declarative-logging/declarative-logging-symbol-processor/src/test/resources/logback.xml
  logging/logging-common/src/main/java/ru/tinkoff/kora/logging/common/annotation/Log.java
  mkdocs/docs/features/declarative-logging.md
  mkdocs/mkdocs.yml
  settings.gradle
  symbol-processor-common/build.gradle
  symbol-processor-common/src/main/kotlin/ru/tinkoff/kora/ksp/common/KotlinPoetUtils.kt
  symbol-processor-common/src/testFixtures/kotlin/ru/tinkoff/kora/ksp/common/AbstractSymbolProcessorTest.kt
  symbol-processors/build.gradle
Labels: new feature

#246 Remove `MicrometerCacheMetrics` duplicate component
  build.gradle
  cache/cache-caffeine/src/main/java/ru/tinkoff/kora/cache/caffeine/AbstractCaffeineCache.java
  cache/cache-caffeine/src/main/java/ru/tinkoff/kora/cache/caffeine/CaffeineCacheTelemetry.java
  cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/AbstractRedisCache.java
  cache/cache-redis/src/main/java/ru/tinkoff/kora/cache/redis/client/LettuceClientFactory.java
  dependencies.gradle
  micrometer/micrometer-module/build.gradle
  micrometer/micrometer-module/src/main/java/ru/tinkoff/kora/micrometer/module/MetricsModule.java
  mkdocs/docs/features/cache.md
Labels: bug
