Repository Tinkoff/kora, pull requests merged in 2023-03, with the labels that each got.

#91 JDBC & R2DBC & Vertx Config changes
  database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/DbUtils.java
  database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/jdbc/JdbcRepositoryGenerator.java
  database/database-annotation-processor/src/main/java/ru/tinkoff/kora/database/annotation/processor/r2dbc/R2dbcRepositoryGenerator.java
  database/database-cassandra/src/main/java/ru/tinkoff/kora/database/cassandra/CassandraConfig.java
  database/database-flyway/src/main/java/ru/tinkoff/kora/database/flyway/FlywayJdbcDatabaseInterceptor.java
  database/database-flyway/src/test/java/ru/tinkoff/kora/database/flyway/FlywayJdbcDatabaseInterceptorTest.java
  database/database-jdbc/src/main/java/ru/tinkoff/kora/database/jdbc/JdbcDatabase.java
  database/database-jdbc/src/main/java/ru/tinkoff/kora/database/jdbc/JdbcDatabaseConfig.java
  database/database-jdbc/src/main/java/ru/tinkoff/kora/database/jdbc/JdbcDatabaseModule.java
  database/database-jdbc/src/test/java/ru/tinkoff/kora/database/jdbc/JdbcDatabaseTest.java
  database/database-r2dbc/src/main/java/ru/tinkoff/kora/database/r2dbc/R2dbcConnectionFactory.java
  database/database-r2dbc/src/main/java/ru/tinkoff/kora/database/r2dbc/R2dbcDatabase.java
  database/database-r2dbc/src/main/java/ru/tinkoff/kora/database/r2dbc/R2dbcDatabaseConfig.java
  database/database-r2dbc/src/main/java/ru/tinkoff/kora/database/r2dbc/R2dbcModule.java
  database/database-r2dbc/src/main/java/ru/tinkoff/kora/database/r2dbc/mapper/result/R2dbcResultColumnMapper.java
  database/database-r2dbc/src/main/java/ru/tinkoff/kora/database/r2dbc/mapper/result/R2dbcRowMapper.java
  database/database-r2dbc/src/test/java/ru/tinkoff/kora/database/r2dbc/R2dbcDatabaseTest.java
  database/database-vertx/src/main/java/ru/tinkoff/kora/database/vertx/VertxDatabaseConfig.java
  database/database-vertx/src/test/java/ru/tinkoff/kora/database/vertx/VertxConnectionFactoryTest.java
  mkdocs/docs/features/container.md
Labels: enhancement

#95 Resilient Module Optimized
  mkdocs/docs/features/cache.md
  mkdocs/docs/features/resilient.md
  mkdocs/docs/features/validation.md
  resilient/resilient-annotation-processor/src/main/java/ru/tinkoff/kora/resilient/annotation/processor/aop/CircuitBreakerKoraAspect.java
  resilient/resilient-retry/src/main/java/ru/tinkoff/kora/resilient/retry/simple/SimpleRetrier.java
Labels: documentation

#97 Cache processing fixed
  cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/CacheKeyAnnotationProcessor.java
  cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/CacheOperation.java
  cache/cache-annotation-processor/src/main/java/ru/tinkoff/kora/cache/annotation/processor/aop/AbstractAopCacheAspect.java
  cache/cache-symbol-processor/src/main/kotlin/ru/tinkoff/kora/cache/symbol/processor/aop/AbstractAopCacheAspect.kt
Labels: bug

#96 Doc markdown fix
  mkdocs/docs/features/cache.md
  mkdocs/docs/features/resilient.md
  mkdocs/docs/features/validation.md
Labels: documentation

#102 fix ViolationException.buildViolationMessage
  validation/validation-common/src/main/java/ru/tinkoff/kora/validation/common/ViolationException.java
Labels: bug
